CREATE TABLE USUARIO(
ID_USUARIO NUMBER NOT NULL,
NOME VARCHAR2(255) NOT NULL,
CPF VARCHAR2(22) NOT NULL,
DATA_NASCIMENTO NUMBER NOT NULL,
SENHA VARCHAR2(100) NOT NULL,

CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO) ENABLE
);

CREATE SEQUENCE S_USER INCREMENT BY 1 START WITH 1 MINVALUE 1;